export const EVENT_CATEGORIES = [
  'Acolhida virtual', 
  'Aula síncrona', 
  'Ciclo de palestras', 
  'Colóquio', 
  'Congresso', 
  'ENAMED', 
  'Encontro Pedagógico', 
  'Encontro Virtual', 
  'Grupo de Estudo', 
  'Iniciação Científica', 
  'Jornada Acadêmica', 
  'Lives Polo Local', 
  'Minicurso', 
  'Momento Síncrono', 
  'Oficina Virtual de Aprendizagem', 
  'Palestras', 
  'Semana acadêmica', 
  'Simpósio', 
  'Webinar',
  'Workshop',
  'Exposição Acadêmica',
  'Fórum de Debates',
  'Mesa Redonda',
  'Seminário de Pesquisa'
];

export const ACADEMIC_COURSES = [
  'Administração',
  'Arquitetura e Urbanismo',
  'ADS - Análise e Desenv. de Sistemas',
  'Biologia (Licenciatura)',
  'Biomedicina',
  'C. Contábeis',
  'Ciência da Computação',
  'Direito',
  'Ed. Física (Bacharelado)',
  'Ed. Física (Licenciatura)',
  'Enfermagem',
  'Engenharia Civil',
  'Engenharia de Produção',
  'Engenharia Elétrica',
  'Estética e Cosmética',
  'Farmácia',
  'Fisioterapia',
  'Gestão de TI',
  'Gestão Financeira',
  'Gestão Hospitalar',
  'Gestão Pública',
  'História',
  'Jornalismo',
  'Letras (Inglês)',
  'Letras (Português)',
  'Marketing',
  'Matemática',
  'Medicina',
  'Medicina Veterinária',
  'Nutrição',
  'Odontologia',
  'Pedagogia',
  'Psicologia',
  'Publicidade e Propaganda',
  'Recursos Humanos',
  'Segurança Pública',
  'Serviço Social',
  'Sistemas de Informação',
  'Teologia'
];
